### ISSUE TITLE
Multiple recipient support

### ISSUE THREAD

**Issue by defkev** [dploeger/disclaimr#3]
If you are sending a mail too more than one recipient (either by having multiple To and/or Cc and probably even Bcc) the rule will fail as soon a recipient isn't matching the regex defined in the requirement.

Now if you are using disclaimr to add a, for example, legal disclaimer to your outgoing message, you are most likely interested in archiving the exact opposite to get a "Add my legal disclaimer to all external messages even if it has a local recipient"-behavior.

Here comes the hack:

In **disclaimr/disclaimr.py** change the **rcpt** function on line **104** from:

``` python
def rcpt(self, recip, cmd_dict):
    ...
    if not self.helper.enabled:
        return lm.CONTINUE
```

to

``` python
def rcpt(self, recip, cmd_dict):
    ...
    if self.helper.rcptmatch:
        logging.debug("We already have a positive recipient match "
                                "so we skip all further checks.")
        return lm.CONTINUE
```

furthermore in **disclaimr/disclaimr/milter_helper.py** add a new property to the ****init**** function around line **40** to look like:

``` python
def __init__(self, configuration):
    ...
    self.rcptmatch = False
```

and change the **rcpt** function in **disclaimr/disclaimr/milter_helper.py** starting at line **104** to look like:

``` python
def rcpt(self, recip, cmd_dict):

    """ Called when the RCPT TO-envelope has been set

    :param recip: The RCPT TO-envelope
    :param cmd_dict: A libmilter command dictionary
    """

    # Check requirements

    for req in models.Requirement.objects.filter(id__in=self.requirements):

        if not re.search(req.recipient, recip):

            self.filter = filter(
                lambda x: x != req.id, self.requirements
            )

            if len(self.filter) == 0:

                logging.debug("Couldn't match the recipient address in any "
                               "requirement. Skipping.")

                self.enabled = False

        else:
            logging.debug("Recipient address matches regex.")

            self.rcptmatch = True
            self.enabled = True

    self.mail_data["envelope_rcpt"] = recip
```

Cheers

**Comment by dploeger** [comment]
@defkev Thank you very much for your contributions. Are you using disclaimr on a regular base? I myself switched departments and am not, so I cannot quite support it well. I'd like to give you push access to this repository so you could add your contributions directly. Are you interested?

**Comment by defkev** [comment]
I am currently testing disclaimr in my lab environment and intend to implement it in production once everything is working.
So yes, go ahead.

**Comment by dploeger** [comment]
Done. Thank you very much!

**Comment by defkev** [comment]
Fixed in RC2
